// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CilGlobeAlt: typeof import('~icons/cil/globe-alt')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    VformItem: typeof import('./../components/molecules/VFormItem/vformItem.vue')['default']
    Vlayout: typeof import('./../components/templates/VLayout/vlayout.vue')['default']
    Vnavbar: typeof import('./../components/organisms/VNavbar/vnavbar.vue')['default']
  }
}

export { }
